# Generated by Django 5.0.2 on 2024-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_autores"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="editora",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
