# Generated by Django 5.0.2 on 2024-07-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_livro_paginas_livro_isbn_livro_quantidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.PROTECT, related_name="livros", to="core.categoria"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.PROTECT, related_name="livros", to="core.autor"
            ),
            preserve_default=False,
        ),
    ]
