# Generated by Django 5.0.2 on 2024-08-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_editora_alter_livro_autores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="coautor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livrosCoautor",
                to="core.autor",
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="autores",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livrosAutor",
                to="core.autor",
            ),
        ),
    ]
